export const GET_ETH_BALANCES = 'GET_ETH_BALANCES';
export const GET_ETH_BALANCES_SUCCESS = 'GET_ETH_BALANCES_SUCCESS';
export const GET_ETH_BALANCES_FAILURE = 'GET_ETH_BALANCES_FAILURE';
export const GET_ETH_BALANCES_EVENT = 'GET_ETH_BALANCES_EVENT';

export const GET_RATES_DATA = 'GET_RATES_DATA';
export const GET_RATES_DATA_SUCCESS = 'GET_RATES_DATA_SUCCESS';
export const GET_RATES_DATA_FAILURE = 'GET_RATES_DATA_FAILURE';
